### ISSUE TITLE
problem with glutin on osx

### ISSUE THREAD

**Issue by jlmitch5** [rsaarelm/magog#1]
I ran magog with `cargo run --release`.

It opens the game window and immediately errors out:

```
     Running `target/release/magog`
Magog v0.1.0-alpha+g2365d6f
rustc 1.0.0-nightly (e2fa53e59 2015-03-20) (built 2015-03-20)

thread '<main>' panicked at 'not yet implemented', /Users/jmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.0.12/src/cocoa/mod.rs:591
thread '<main>' panicked at 'not yet implemented', /Users/jmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.0.12/src/cocoa/mod.rs:591
stack backtrace:
   1:        0x1082b75df - sys::backtrace::write::hadb1455a57ee2267A7C
   2:        0x1082b863d - panicking::on_panic::hb14107ef264d170efXI
   3:        0x1082aea59 - rt::unwind::begin_unwind_inner::h8da2f07c00df904aZFI
   4:        0x10823976f - rt::unwind::begin_unwind::h15946664856272882207
   5:        0x108218262 - backend::Rc<T>.Backend::is_current::h646504145715981977
   6:        0x1081f202d - context::Context::make_current::h209a50ce9a80ee6a72u
   7:        0x1081f21b9 - DisplayImpl.Drop::drop::hca38c6a63bd351c4t5U
   8:        0x1081da0c2 - glium..DisplayImpl::drop.7404::h8481bf0a6cf36476
   9:        0x1081d32b9 - canvas::CanvasBuilder::run::ha447817254992976Nda
  10:        0x1081c9a2b - main::had79dfd8d394f317PQb
  11:        0x1082c9e68 - rust_try_inner
  12:        0x1082c9e55 - rust_try
  13:        0x1081ccbbe - main
thread panicked while panicking. aborting.
An unknown error occurred

To learn more, run the command again with --verbose.
```

**Comment by rsaarelm** [comment]
I don't have a Mac so I can't test this directly, but it looks like the function on that line has been given an implementation in the current Glutin master, while it's still marked as unimplemented and causing the runtime crash the crates.io version Magog is using.

If you know how to mess with Cargo files, you could change glutin to be fetched from the github master instead of the crates.io version (actually I think you'll need to get a local copy of calx, change its Cargo.toml since that's where glium is being referenced, then point your local magog's Cargo.toml to your local calx, then try again).

If you haven't been already troubleshooting Cargo configs by hand and that sounds too confusing, you can just wait for the updated Glium to end up on crates.io and then either take your chances doing a "cargo update" on magog yourself or wait for me to release the next "Updated dependencies/to latest Rust" commit.

**Comment by jlmitch5** [comment]
Funny you should mention the dependency thing...I'm a bit embarrassed to say I spent several hours playing around with Cargo dependencies yesterday trying to get things updated so Magog would compile on yesterday's nightly...until I saw your note on Phage that I should use the version you compiled with.

Also a question about dependency stuff if you don't mind me asking: is there an easy way to tell where the crates.io container is actually at in terms of the repo?  I've noticed that people will commit "bump to x version", even when they haven't pushed that to Cargo.  This makes it pretty hard to try to fix things.

**Comment by rsaarelm** [comment]
After a quick look-around, I didn't see anything associating the crates containers with git hashes. Makes sense, someone might want to push things to crates without having any kind of public git repository for it, so crates might have just the file set snapshots and semver numbers.

**Comment by jlmitch5** [comment]
yeah...you get like thread '<main>' panicked at 'not yet implemented', /Users/jmitchell/.cargo/registry/src/github.com-**1ecc6299db9ec823**/glutin-0.0.12/src/cocoa/mod.rs:591

but that doesn't seem to be related to a commit hash.

**Comment by jlmitch5** [comment]
So to hand update nested dependencies, you need to fork each library and specify the dependency in its Cargo.toml, correct?

**Comment by rsaarelm** [comment]
If you want to try a quick and dirty approach, you can just go in your ~/.cargo folder and put a different fileset in the directory where it builds the package from. If the libraries have some simple oneliner fixes they need to build with the latest Rust, I generally just edit the sources in the ~/.cargo cache directly to do trivial changes. Haven't tried changing the whole fileset, but it might work as well if the versions are close to each other.

**Comment by rsaarelm** [comment]
OSX should be working now.
